USE practice_db;

DROP TABLE IF EXISTS ads;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
id INT USNIGNED NOT NULL AUTO_INCREMENT,
username VARCHAR(240) NOT NULL,
email VARCHAR(240) NOT NULL,
password VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE ads (
id INT UNSIGNED NOT NULL,
user_id INT UNSIGNED NOT NULL,
title VARCHAR(240) NOT NULL,
PRIMARY KEY (id),
FOREGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
);